### ISSUE TITLE
Unhelpful error message for alignment files with missing read groups

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/avocado#291]
```
$ avocado-submit \
 ... \
 -- \
 biallelicGenotyper \
 missing-rg.bam \
 missing-rg.genotypes.adam
...

18/02/09 16:10:13 INFO Client:
     client token: N/A
     diagnostics: User class threw exception: java.lang.IllegalArgumentException:
requirement failed: Currently, we only support a single sample. Saw: .
     ApplicationMaster host: ...
     ApplicationMaster RPC port: 0
     queue: default
     start time: 1518192582824
     final status: FAILED
     tracking URL: http://.../proxy/application_1518191381165_0005/
     user: hadoop
Exception in thread "main" org.apache.spark.SparkException: Application application_1518191381165_0005 finished with failed status
    at org.apache.spark.deploy.yarn.Client.run(Client.scala:1122)
    at org.apache.spark.deploy.yarn.Client$.main(Client.scala:1168)
    at org.apache.spark.deploy.yarn.Client.main(Client.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
18/02/09 16:10:13 INFO ShutdownHookManager: Shutdown hook called
```

Worked fine after adding `RecordGroup`(s)
```
$ adam-shell

val alignments = sc.loadAlignments("missing-rg.bam")
val withRecordGroups = alignments.replaceRecordGroups(RecordGroupDictionary(Seq(RecordGroup("sample", "sample"))))
withRecordGroups.saveAsParquet("missing-rg.alignments.adam")

$ avocado-submit \
 ... \
 -- \
 biallelicGenotyper \
 missing-rg.alignments.adam \
 missing-rg.genotypes.adam
...
```

**Comment by heuermh** [comment]
Thanks!
